name: "📚 [Short] Paper Review Template"
description: "[속독] 논문 정리를 위한 template version.1.0."
body:
  - type: textarea
    id: review
    attributes:
      label: Review
      description: Simple review! please add a figure.
      placeholder: 자유 요약(figure 첨부 필수)
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Paper URL
      placeholder: 논문 링크
    validations:
      required: true
